services:
  api:
    image: ghcr.io/rubenhensen/lingo-api:latest
    ports:
      - "8000:80"
    environment:
      - PHP_DISPLAY_ERRORS=0
    restart: unless-stopped

  frontend:
    image: ghcr.io/rubenhensen/lingo-frontend:latest
    ports:
      - "8001:80"
    depends_on:
      - api
    restart: unless-stopped
