version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:80"
    environment:
      - PHP_DISPLAY_ERRORS=0
    volumes:
      - ./api:/var/www/html
    restart: unless-stopped

  frontend:
    build:
      context: ./website
    ports:
      - "8001:80"
    volumes:
      - ./website:/usr/share/nginx/html
      - ./local-config.js:/usr/share/nginx/html/js/config.js
    depends_on:
      - api
    restart: unless-stopped
